---
ocp_vms_copy_method: qemu-img
ocp_vms_cpu_passthrough: True
ocp_vms_no_log: False
ocp_vms_preprovisioned: False
ocp_vms_preprovisioned_basename: ocpbacking-x86_64-kvm.qcow2
ocp_vms_password: ocp4ever
ocp_vms_libvirt_images_location: /var/lib/libvirt/images
ocp_vms_net_cidr: 10.0.0.0/24
ocp_vms_net_nat: True
ocp_vms_utility_os: rhel7
ocp_vms_utility_name: util
ocp_vms_utility_cpus: 1
ocp_vms_utility_size: 30
ocp_vms_storage_name: storage
ocp_vms_storage_cpus: 2
ocp_vms_storage_size: 30
ocp_vms_bootstrap_cpus: 2
ocp_vms_bootstrap_memory: 4096
ocp_vms_master_count: 3
ocp_vms_master_cpus: 4
ocp_vms_master_memory: 8192
ocp_vms_infra_count: 2
ocp_vms_infra_cpus: 4
ocp_vms_infra_memory: 4096
ocp_vms_worker_count: 2
ocp_vms_worker_cpus: 4
ocp_vms_worker_memory: 4096
ocp_vms_hugepages: False
ocp_vms_storage_overcommit: False
ocp_vms_console: True
ocp_vms_no_auto_vm_console: True
ocp_vms_el_url: http://packages.oit.ncsu.edu/centos/7/os/x86_64
ocp_vms_openshift_release: 4.2
ocp_vms_openshift_subdomain: ocp4
ocp_vms_openshift_rootdomain: example.com
ocp_vms_openshift_pullsecret_file: pull-secret.txt
# These dictionaries are primarily used for creating the QCOW2 files.
ocp_vms_utility_node:
  - name: "{{ ocp_vms_utility_name }}"
    # Size in gigabytes.
    size: 30
    # Size in megabytes.
    ram: 1024
ocp_vms_storage_node:
  - name: "{{ ocp_vms_storage_name }}"
    # Primary disk size in gigabytes.
    size: 30
    # Data disk size in gigabytes.
    datadisksize: 200
    # Size in megabytes.
    ram: 1024
# The names are also used to create the virtual machines.
ocp_vms_bootstrap_node:
  - name: bootstrap
    size: 40
    ram: 4096
ocp_vms_master_nodes:
  - name: master
    size: 120
    ram: 8192
ocp_vms_infra_nodes:
  - name: infra
    size: 120
    ram: 4096
ocp_vms_worker_nodes:
  - name: worker
    size: 120
    ram: 4096
