---
# !/usr/bin/env ansible-playbook

# - name: Configure hypervisor host
#   ansible.builtin.import_playbook: playbooks/00-ocp-hyper.yaml
- name: Provision KVM virtual machines
  ansible.builtin.import_playbook: playbooks/01-ocp-vms.yaml
- name: Configure utility node
  ansible.builtin.import_playbook: playbooks/02-ocp-util-node.yaml
- name: Initialize OpenShift cluster
  ansible.builtin.import_playbook: playbooks/03-ocp-init.yaml
- name: Clear kernel page cache
  ansible.builtin.import_playbook: playbooks/clear-cache.yaml
