---
# Post OCP4 Solo Lab install - external NFS provisioner configuration

- name: Create NFS Provisioner artifacts directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner"
    state: directory
    mode: "0755"

- name: Pull NFS Provisioner manifests
  ansible.builtin.get_url:
    url: "{{ ocp_nfs_ext_provision_github_url }}{{ item }}"
    dest: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner"
    mode: "0440"
  loop:
    - rbac.yaml
    - deployment.yaml
    - class.yaml

# Update manifests to use UTIL_IP, proper NFS dirs, proper NAMESPACE, and custom class name
- name: Update rbac.yaml
  block:
    - name: >-
        Sed replace ==> s/namespace:.*/namespace: $NAMESPACE/g ==> rbac.yaml
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/rbac.yaml"
        regexp: >-
          namespace:.*
        replace: >-
          namespace: '{{ ocp_nfs_ext_provision_namespace }}'

- name: Update deployment.yaml
  block:
    - name: >-
        Sed replace ==> s/namespace:.*/namespace: $NAMESPACE/g ==> deployment.yaml
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/deployment.yaml"
        regexp: >-
          namespace:.*
        replace: >-
          namespace: '{{ ocp_nfs_ext_provision_namespace }}'

    - name: >-
        Sed replace ==> s/10.3.243.101/$UTIL_IP/g ==> deployment.yaml
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/deployment.yaml"
        regexp: >-
          10.3.243.101
        replace: >-
          '{{ util.ipaddr }}'
    - name: >-
        Sed replace ==> s/fuseim.*/storage.io\/nfs/g ==> deployment.yaml
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/deployment.yaml"
        regexp: >-
          fuseim.*
        replace: >-
          storage.io/nfs

    - name: >-
        Sed replace ==> s/\/ifs\/kubernetes/\/mnt\/nfs\/ocp/g ==> deployment.yaml
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/deployment.yaml"
        regexp: >-
          /ifs/kubernetes
        replace: >-
          /mnt/nfs/ocp

- name: Update class.yaml
  block:
    - name: >-
        Sed replace ==> s/fuseim.*/storage.io\/nfs/g ==> class.yaml
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/class.yaml"
        regexp: >-
          fuseim.*
        replace: >-
          storage.io/nfs

    - name: >-
        Sed replace ==> s/nfs-client/managed-nfs-storage/g ==> class.yaml
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/class.yaml"
        regexp: >-
          name: nfs-client
        replace: >-
          name: managed-nfs-storage

- name: Create the NFS External Provisioner namespace
  kubernetes.core.k8s:
    name: "{{ ocp_nfs_ext_provision_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Apply openshift.io/cluster-monitoring=true label to NFS provisioner namespace
  ansible.builtin.command: >-
    oc label namespace '{{ ocp_nfs_ext_provision_namespace }}' "openshift.io/cluster-monitoring=true"
  register: oc_label_namespace_result
  changed_when: '"labeled" in oc_label_namespace_result.stdout'
  failed_when: false

- name: Fail if namespace label apply did not succeed
  ansible.builtin.fail:
    msg:
      - "stdout: {{ oc_label_namespace_result.stdout }}"
      - "stderr: {{ oc_label_namespace_result.stderr }}"
  when: >-
    "already has a value (true)" not in oc_label_namespace_result.stderr and
    "labeled" not in oc_label_namespace_result.stdout

- name: Stdout for "oc label namespace"
  ansible.builtin.debug:
    msg: "{{ oc_label_namespace_result.stdout }}"

- name: Apply RBAC manifest ==> ServiceAccount, ClusterRole, ClusterRoleBinding, Role, RoleBinding
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/rbac.yaml"
    wait: true

- name: Add hostmount-anyuid SCC to nfs-client-provisioner service account
  ansible.builtin.command: "oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:{{ ocp_nfs_ext_provision_namespace }}:nfs-client-provisioner"
  register: oc_adm_policy_result
  changed_when: '"added" in oc_adm_policy_result.stdout'
  failed_when: '"added" not in oc_adm_policy_result.stdout'

- name: Apply StorageClass manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/class.yaml"
    wait: true

- name: Apply Deployment manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_user_dir }}/ocp4upi/artifacts/nfs-external-provisioner/deployment.yaml"
    wait: true

- name: Set class as cluster-wide default
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: managed-nfs-storage
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
    wait: true

- name: Pause for 10 seconds...
  ansible.builtin.pause:
    seconds: 10

- name: Fetch configs.imageregistry.operator.openshift.io/cluster to determine registry status
  kubernetes.core.k8s_info:
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
  register: imageregistry_config_list

- name: Set fact for registry status
  ansible.builtin.set_fact:
    imageregistry_status: "{{ imageregistry_config_list | json_query(my_query) | first | json_query('Status') }}"
  vars:
    my_query: "resources[].{Status: status.conditions[?type=='Available'].message|[0]}"

- name: Check registry status
  ansible.builtin.debug:
    msg: "Registry status: {{ imageregistry_status }}"

- name: Pause for 45 seconds to allow NFS storage configuration to settle
  ansible.builtin.pause:
    seconds: 45
  when: >-
    "The registry is ready" not in imageregistry_status

- name: Set Image Registry to use NFS storage
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        managementState: Managed
        storage:
          pvc:
            claim: ""
    wait: true
  when: >-
    "The registry is ready" not in imageregistry_status

- name: Re-verify registry status block
  when: >-
    "The registry is ready" not in imageregistry_status
  block:
    - name: Pause for 45 seconds to allow Image Registry Operator cluster config to update
      ansible.builtin.pause:
        seconds: 45
    - name: Fetch configs.imageregistry.operator.openshift.io/cluster to determine registry status
      kubernetes.core.k8s_info:
        api_version: imageregistry.operator.openshift.io/v1
        kind: Config
      register: imageregistry_config_list

    - name: Set fact for registry status
      ansible.builtin.set_fact:
        imageregistry_status: "{{ imageregistry_config_list | json_query(my_query) | first | json_query('Status') }}"
      vars:
        my_query: "resources[].{Status: status.conditions[?type=='Available'].message|[0]}"

    - name: Check registry status
      ansible.builtin.debug:
        msg: "Registry status: {{ imageregistry_status }}"
