---
# Post OCP4 Solo Lab install - OCP pip modules

- name: Install kubernetes, openshift, jmespath pip modules for Python 3, using the 'pip3' executable.
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  with_items:
    - kubernetes
    - openshift
    - jmespath
