---
# Post OCP4 Solo Lab install - OCP pip modules

- name: Install kubernetes and openshift modules for Python 3, using the 'pip3' executable.
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  with_items:
    - kubernetes==11.0.0
    - openshift==0.11.2
