---
- name: Boot VM
  community.libvirt.virt:
    name: "{{ dns.clusterid }}.{{ item.name }}"
    state: running

- name: Pause for 30 seconds to allow multiple boot offsets
  ansible.builtin.pause:
    seconds: 30
