---
- name: Create OpenShift infrastructure virtual machines
  command: >
    virt-install
    --name {{ ocp_vms_openshift_subdomain }}.{{ ocp_vms_infra_nodes[0].name }}{{ item }}
    --cpu=host --vcpus {{ ocp_vms_infra_cpus }}
    --memory {{ ocp_vms_infra_nodes[0].ram }}
    {% if ocp_vms_hugepages == true %}--memorybacking hugepages=on{% endif %}
    --os-variant rhel8.0
    {% if ocp_vms_cpu_passthrough %}--cpu host-passthrough{% endif %}
    --controller type=scsi,model=virtio-scsi
    --disk path={{ ocp_vms_libvirt_images_location }}/{{ ocp_vms_openshift_subdomain }}-{{ ocp_vms_infra_nodes[0].name }}{{ item }}.qcow2,bus=scsi,discard='unmap',format=qcow2,size={{ ocp_vms_infra_nodes[0].size }}
    --network network={{ ocp_vms_openshift_subdomain }}-private,model=virtio,mac={{ '52:54:00' | random_mac }}
    --boot hd,network,menu=on --noreboot
    {% if ocp_vms_console %}
    --console pty,target_type=virtio
    {% endif %}
    {% if ocp_vms_no_auto_vm_console %}
    --noautoconsole
    {% endif %}
    {% if ocp_vms_storage_overcommit %}
    --check disk_size=off
    {% endif %}
  with_sequence: start=0 end={{ ocp_vms_infra_num|int -1 }} format=%02x

- name: start infra VM mac address ini section
  shell: >
    echo "" >> /tmp/vm_mac_addrs.ini;
    echo "[infras]" >> /tmp/vm_mac_addrs.ini
  tags:
    - vm_mac_dict

- name: record infra VM mac address
  shell: >
    itemmac=$(virsh domiflist {{ ocp_vms_openshift_subdomain }}.{{ ocp_vms_infra_nodes[0].name }}{{ item }} | grep -i {{ ocp_vms_openshift_subdomain }}-private | awk '{print $5}');
    echo "{{ ocp_vms_infra_nodes[0].name }}{{ item }}.mac=$itemmac" >> /tmp/vm_mac_addrs.ini
  with_sequence: start=0 end={{ ocp_vms_infra_num|int -1 }} format=%02x
  tags:
    - vm_mac_dict

- name: "Append dict seq - infras"
  vars:
    infra_vm: "{{ ocp_vms_infra_nodes[0].name }}{{ item }}"
    infra_mac: "{{ lookup('ini', '{{ ocp_vms_infra_nodes[0].name }}{{ item }}.mac section=infras file=/tmp/vm_mac_addrs.ini') }}"
  set_fact:
    infra_dict: "{{ infra_dict | default({}) | combine( { infra_vm : infra_mac } ) }}"
  with_sequence: start=0 end={{ ocp_vms_infra_num|int -1 }} format=%02x
  tags:
    - vm_mac_dict