---
# Setup OCP4 Solo Lab Hypervisor Node

- name: Install base packages
  yum:
    name:
      - vim
      - bash-completion
      - podman
      - "@virtualization"
      - guestfs-browser
      - libguestfs-tools
      - python-libguestfs
      - virt-top
      - ksmtuned
    state: present
  when:
      - ansible_distribution == 'Fedora'

- name: "Starting {{ item }} service"
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - ksm
    - ksmtuned

- name: Install libselinux-python package
  yum:
    name:
      - libselinux-python
  when:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
