---
# Setup OCP4 Solo Lab Hypervisor Node

- name: Install base packages on Fedora
  dnf:
    name:
      - vim
      - bash-completion
      - podman
      - "@virtualization"
      - guestfs-browser
      - libguestfs-tools
      - python-libguestfs
      - virt-top
      - ksmtuned
      - python2-netaddr
      - python3-netaddr
    state: present
  when:
      - ansible_distribution == 'Fedora'

- name: Install base packages on CentOS/RHEL
  yum:
    name:
      - vim
      - bash-completion
      - podman
      - "@virtualization-hypervisor"
      - "@virtualization-client"
      - "@virtualization-platform"
      - "@virtualization-tools"
      - iptables-services
      - libguestfs-tools
      - libguestfs-xfs
      - python-lxml
      - python-netaddr
    state: present
  when:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: "Starting {{ item }} service"
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - ksm
    - ksmtuned

- name: Install libselinux-python package
  yum:
    name:
      - libselinux-python
  when:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
