---
# build and configure dhcp server container
- name: Ensure group "dhcpd" exists
  ansible.builtin.group:
    name: dhcpd
    gid: 177
    state: present

- name: Ensure "dhcpd" user exists
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    comment: "{{ item.comment }}"
    home: "{{ item.home }}"
    uid: "{{ item.uid }}"
    state: present
    shell: "{{ item.shell }}"
  with_items:
    - { name: "dhcpd", group: "dhcpd", comment: "DHCP server", home: "/", uid: 177, shell: "/sbin/nologin" }

- name: Dhcpd container config and leases dirs
  ansible.builtin.file:
    path: /srv/cntr_mounts/dhcpd/{{ item }}
    state: directory
    owner: dhcpd
    group: dhcpd
    mode: "0755"
  with_items:
    - leases
    - configs

- name: Ensure leases db file is present on host system
  ansible.builtin.file:
    path: "/srv/cntr_mounts/dhcpd/leases/dhcpd.leases"
    state: touch
    mode: u=rw,g=r,o=r
    owner: dhcpd
    group: dhcpd

- name: Write out dhcp config file
  ansible.builtin.template:
    src: dhcp/dhcpd.conf.j2
    dest: /srv/cntr_mounts/dhcpd/configs/dhcpd.conf
    owner: dhcpd
    group: dhcpd
    mode: "0640"

- name: Prep base container image
  ansible.builtin.import_role:
    name: v1-cntr-img-build-prep

- name: Add the newly created container to the inventory
  ansible.builtin.add_host:
    hostname: "{{ container_name }}"
    ansible_connection: "{{ container_engine }}"
    ansible_python_interpreter: /usr/bin/python3 # fedora container doesn't ship python2
    ansible_become: true
    become_user: root

- name: Run the role in the container
  delegate_to: "{{ container_name }}"
  ansible.builtin.import_role:
    name: util-dhcp-cntr

- name: Build and commit DHCP container image (buildah)
  when: container_engine == 'buildah'
  block:
    - name: Set default command for DHCP container image
      ansible.builtin.command: >
        buildah config --cmd "/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid" {{ container_name }}
      changed_when: true

    - name: Check if DHCP image already exists
      ansible.builtin.command: podman inspect localhost/{{ image_name }}:latest
      register: inspectout
      changed_when: false
      failed_when: false

    - name: Remove existing DHCP image before re-commit
      ansible.builtin.command: podman rmi localhost/{{ image_name }}:latest
      changed_when: true
      when: '"error getting image" not in inspectout.stderr'

    - name: Commit build container to DHCP image
      ansible.builtin.command: "buildah commit --rm {{ container_name }} {{ image_name }}:latest"
      changed_when: true

- name: Build and commit DHCP container image (docker)
  when: container_engine == 'docker'
  block:
    - name: Commit build container to DHCP image
      ansible.builtin.command: >
        docker commit
        -c 'CMD ["/usr/sbin/dhcpd", "-f", "-cf", "/etc/dhcp/dhcpd.conf", "-user", "dhcpd", "-group", "dhcpd", "--no-pid"]'
        {{ container_name }} {{ image_name }}
      changed_when: true

    - name: Remove the build container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
