---
- name: Provision KVM virtual machines for OCP4 Solo Lab
  hosts: hypervisor
  become: true
  vars:
    # Separate infra/worker count vars avoid "to count backwards make stride negative"
    # errors when 0 nodes of either type are specified
    ocp_vms_infra_num: "{{ 1 | int if ocp_vms_infra_count == 0 else ocp_vms_infra_count }}"
    ocp_vms_worker_num: "{{ 1 | int if ocp_vms_worker_count == 0 else ocp_vms_worker_count }}"
  tasks:
    - name: Show infra and worker node counts
      ansible.builtin.debug:
        msg: "ocp_vms_infra_num ==> {{ ocp_vms_infra_num }} -- ocp_vms_infra_count ==> {{ ocp_vms_infra_count }}"

    - name: Deploy VMs for OCP4 Solo Lab
      ansible.builtin.import_role:
        name: ocp4_solo_vmprovision
