---
- hosts: hypervisor
  become: true
  tasks:
  - name: start util vm
    virt:
      name: "{{ dns.clusterid }}.{{ util.name }}"
      state: running
    when:
      - ocp_vms_util_node

- hosts: util
  become: true
  gather_facts: no
  tasks:
  - name: Wait for connection...
    wait_for_connection:
      delay: 10
      timeout: 120
    when:
      - ocp_vms_util_node

- hosts: util
  become: true
  tasks:
  - name: "RHN registration and repo enablement"
    import_role:
      name: devnullcake.redhat-subscription
    vars:
      redhat_subscription_enable_explicit_repos_only: "yes"
      redhat_subscription_disable_repos: []
      redhat_subscription_enable_repos:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
    when:
      - ansible_distribution == 'RedHat'
      - ocp_vms_util_node

  - name: "Configure utility node"
    import_role:
      name: ocp4-solo-utilnode
    when:
    - ocp_vms_util_node
