---
- hosts: hypervisor
  become: true
  tasks:
  - name: start util vm
    virt:
      name: "{{ dns.clusterid }}.{{ util.name }}"
      state: running
    when:
      - ocp_vms_util_node

- hosts: util
  become: true
  gather_facts: true
  tasks:
  - name: Wait for connection...
    wait_for_connection:
      delay: 10
      timeout: 120
    when:
      - ocp_vms_util_node

- hosts: util
  become: true
  tasks:
  - name: "RHN registration and repo enablement - RHEL7"
    import_role:
      name: devnullcake.redhat-subscription
    vars:
      redhat_subscription_enable_explicit_repos_only: "yes"
      redhat_subscription_disable_repos: []
      redhat_subscription_enable_repos:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
    register: registration_result
    failed_when: registration_result.rc != 0 and "This system is already registered" not in registration_result.stderr
    when:
      - ansible_distribution == 'RedHat' and ansible_distribution_major_version|int <= 7
      - ocp_vms_util_node

  - name: "RHN registration and repo enablement - RHEL8"
    import_role:
      name: devnullcake.redhat-subscription
    vars:
      redhat_subscription_enable_explicit_repos_only: "yes"
      redhat_subscription_disable_repos: []
      redhat_subscription_enable_repos: []
    register: registration_result
    failed_when: registration_result.rc != 0 and "This system is already registered" not in registration_result.stderr
    when:
      - ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 8
      - ocp_vms_util_node

  - name: "Configure utility node"
    import_role:
      name: ocp4-solo-utilnode
    when:
    - ocp_vms_util_node
