---
- hosts: hypervisor
  tasks:
  - name: start bootstrap vm
    virt:
      name: "{{ dns.clusterid }}.{{ bootstrap.name }}"
      state: running

  - name: Pause for 1 minute to allow bootstrap vm to come up and update to latest OS release
    pause:
      seconds: 60

- hosts: hypervisor
  tasks:
  - name: Start master vm(s)
    include_tasks: includes/virt-node-start.yaml
    with_items:
    - "{{ masters }}"

  - name: Pause for 3 minutes to allow master vm(s) to come up and update to latest OS release
    pause:
      seconds: 180

- hosts: util
  become: true
  gather_facts: true
  tasks:
  - name: Execute openshift-install to get to bootstrap completion...
    command: "openshift-install --dir={{ ansible_user_dir }}/ocp4upi wait-for bootstrap-complete --log-level debug"

  - name: >
      Wait until the string "It is now safe to remove the bootstrap resources" is in the file .openshift_install.log before continuing...
    wait_for:
      path: "{{ ansible_user_dir }}/ocp4upi/.openshift_install.log"
      search_regex: It\ is\ now\ safe\ to\ remove\ the\ bootstrap\ resources
      timeout: 6000
      sleep: 10
  tags:
    - ocp_install_log_wait

- hosts: hypervisor
  tasks:
  - name: Remove bootstrap VM
    include_tasks: includes/eject-bootstrap.yaml

  - name: start worker vm(s)
    virt:
      name: "{{ dns.clusterid }}.{{ item.name }}"
      state: running
    with_items:
    - "{{ workers }}"
    when: workers | length > 0

  - name: start infra vm(s)
    virt:
      name: "{{ dns.clusterid }}.{{ item.name }}"
      state: running
    with_items:
    - "{{ infras }}"
    when: infras | length > 0

  - name: Pause for 2 minutes to allow worker vm(s) to come up
    pause:
      seconds: 120
    when: workers | length > 0 or infras | length > 0

- hosts: util
  become: true
  gather_facts: true
  tasks:
  - name: Execute openshift-install again to achieve 100% completion...
    command: "openshift-install --dir={{ ansible_user_dir }}/ocp4upi wait-for install-complete --log-level debug"
    async: 6000
    poll: 0

  - name: >
      Wait until the string "Working towards 4.x.y: 99% complete" is in the file .openshift_install.log before continuing...
    wait_for:
      path: "{{ ansible_user_dir }}/ocp4upi/.openshift_install.log"
      search_regex: Working\ towards\ 4\.(.*)\ 99\%\ complete
      timeout: 2000
      sleep: 10

  - debug:
      msg: "Complete storage setup now..."
 
  - name: >
      Wait until the string "Install complete!" is in the file .openshift_install.log before continuing...
    wait_for:
      path: "{{ ansible_user_dir }}/ocp4upi/.openshift_install.log"
      search_regex: Install complete\!
      timeout: 2000
      sleep: 10
