---
- name: Gather local user and playbook context facts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Capture ansible-playbook working directory
      run_once: true
      ansible.builtin.set_fact:
        ansible_playbook_pwd: "{{ lookup('env', 'PWD') }}"
      failed_when: ansible_playbook_pwd == ''

    - name: Capture current local user name
      run_once: true
      ansible.builtin.set_fact:
        ansible_local_user: >-
          {{ lookup('pipe', 'id -un') | d(lookup('pipe', 'whoami'), True)
          | d(lookup('env', 'USER'), True) | d(lookup('env', 'user'), True)
          | d(lookup('env', 'LOGNAME'), True) }}
      failed_when: ansible_local_user == ''

    - name: Capture current local group name
      run_once: true
      ansible.builtin.set_fact:
        ansible_local_group: "{{ lookup('pipe', 'id -gn') }}"
      failed_when: ansible_local_group == ''

- name: Install OCP pip modules on utility node
  hosts: util
  become: true
  gather_facts: false
  tasks:
    - name: Wait for util node connection
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 120

    - name: Install pip modules for OCP/K8s
      ansible.builtin.import_role:
        name: ocp4_solo_post_install
        tasks_from: ocp-pip-modules

- name: Query cluster details
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Query cluster details for OCP4 Solo Lab
      ansible.builtin.import_role:
        name: ocp4_solo_post_install
        tasks_from: query-cluster
      delegate_to: util

# Included as a reference for debugging
- name: Display inventory debug information
  hosts: "*"
  tags: storage_node_dns
  tasks:
    - name: Display inventory-related ansible variables
      block:
        - name: Show ansible_host
          ansible.builtin.debug:
            var: ansible_host

        - name: Show inventory_hostname
          ansible.builtin.debug:
            var: inventory_hostname

        - name: Show ansible_hostname
          ansible.builtin.debug:
            var: ansible_hostname
