#vim: set ft=ansible:
---
- hosts: util
  become: true
  tasks:
  - name: "OCP pip modules"
    import_role:
      name: ocp4-solo-post-install
      tasks_from: ocp-pip-modules

  - name: "NFS Storage config"
    import_role:
      name: ocp4-solo-post-install
      tasks_from: nfs-storage

  - name: Information about this install 
    vars: 
      msg: |
        "Once the playbook run is complete, ssh into the util vm and run:"
        "# /usr/local/bin/utilnodecheck"
        "...for installation status and details."
    debug: 
      msg: "{{ msg.split('\n') }}"       
    tags: debug_info
