---
# Clear kernel cache

- name: Clear kernel page cache on cluster nodes
  hosts: util masters infras workers
  become: true
  gather_facts: false

  pre_tasks:
    - name: Clear memory cache
      ansible.builtin.raw: "sync; echo 3 > /proc/sys/vm/drop_caches"
      changed_when: false
